# Generated by Django 3.0.8 on 2020-08-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_recognition', '0003_auto_20200826_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerphoto',
            name='img',
            field=models.ImageField(upload_to='flowers/'),
        ),
    ]
